import java.util.ListResourceBundle;

public class bundle_en_AU extends ListResourceBundle {
    public Object[][] getContents() {
        return contents;
    }

    private Object[][] contents = {
            {"titleAuth", "Authorisation"},
            {"login", "Login"},
            {"password", "Password"},
            {"signUp", "Sign Up"},
            {"logIn", "Log In"},
            {"logTooShort", "Login must be at least 3 characters long"},
            {"passTooShort", "Password must be at least 3 characters long"},
            {"userAlreadyExists", "User already exists"},
            {"wrongEmail", "Wrong Email Address"},
            {"userDoesntExist", "User doesn't exist"},
            {"waiting", "Waiting..."},
            {"wrongPassword", "Wrong password"},
            {"token", "Token:"},
            {"deadToken", "Your time limit is over"},
            {"wrongToken", "Wrong Token"},
            {"signUpError", "Sign Up failed"},
            {"SQLException", "Data base is unavailable"},
            {"incorrectCommand", " Command is incorrect"},
            {"send", "Send"},
            {"title", "Creature Collection Viewer"},
            {"language", "Language"},
            {"exit", "exit"},
            {"info", "Creature info"},
            {"name", "Name"},
            {"family", "Family"},
            {"hunger", "Hunger"},
            {"location", "Location"},
            {"creationTime", "Creation time"},
            {"time", "Time"},
            {"inventory", "Inventory"},
            {"user", "User"},
            {"format", "format"},
            {"size", "Size"},
            {"change", "Change"},
            {"cancel", "Cancel"},
            {"refresh", "Refresh"},
            {"disconnected", "Server is unavailable"},
            {"connected", "Connection: true"},
            {"AddedSuccess", "Added Success"},
            {"RemovedSuccess", "Removed Success"},
            {"SavedSuccess", "Saved Success"},
            {"AddedFailing", "Added Failing"},
            {"RemovedFailingDontYours", "Removed Failing: Creature doesn't Yours!"},
            {"SavedFailing", "Saved failing"},
            {"loadFileError", "Load file failing"},
            {"JSONError", "Invalid JSON format"},
            {"greeting", "I wonder what will happen..."},
            {"newCreature", "New"},
            {"creatures", "creatures"},
            {"add", "Add"},
            {"add_if_max", "Add if Max"},
            {"remove", "Remove"},
            {"isEmpty", "field is empty!"},
            {"isnNumber", "value is not a number!"},
            {"isnPositive", "can be positive!"},
            {"isnChosen", "isn't chosen"},
            {"added", "Added"},
            {"tryAgain", "Server is unavailable, try again later"},
            {"incorrectDate", "Date format is"},
            {"ChangedSuccess", "Changed Success"},
            {"ChangedFailing", "Changed Failing"},
            {"ChangedFailingDontYours","Changed Failing: Creature doesn't Yours!"},
            {"windowWillBeClosed", "Dead Token. Window will be closed!"},
            {"incorrectX", "Incorrect X!"},
            {"incorrectY", "Incorrect Y!"},
            {"incorrectSize", "Incorrect Size!"},
            {"incorrectHunger", "Incorrect Hunger!"},
            {"incorrectDate", "Incorrect Date"},
            {"NoCreaturesFound", "No Creatures found"},
            {"deleted", "Deleted"},
            {"kek", "You are not connected<br>LOL"},
            {"color", "Color"},
            {"clear", "Clear"},
            {"CreaturesDoesntChanged", "Creatures didnt't changed"},
            {"ChangedFailedCreatureExists", "Changed Failed: Creature Exists"},
            {"AddedFailedCreatureExists", "Added Failed: Creature Exists"},
    };
}

